services:
  authority-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: authority-image:latest
    env_file:
      - .env.authority  # Specify the environment file
    command: ["yarn", "run", "start:authority", "1"] # Start authority 1
    ports:
      - "3000:3000"
    networks:
      - authority-network

  authority-2:
    image: authority-image:latest
    env_file:
      - .env.authority
    command: ["yarn", "run", "start:authority", "2"]
    ports:
      - "3001:3001"
    networks:
      - authority-network

  # Repeat similarly for authority-3, authority-4, and authority-5

networks:
  authority-network:
    driver: bridge